services:
  postgres:
    image: postgres:16
    container_name: orderfy-postgres
    environment:
      POSTGRES_USER: orderfy
      POSTGRES_PASSWORD: orderfy123
      POSTGRES_DB: orderfy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
